server:
  port: 8081
  forward-headers-strategy: framework
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_omnio
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    properties:
      hibernate:
        format-sql: true
    open-in-view: false
jakarta:
  persistence:
    sharedCache:
      mode: ENABLE_SELECTIVE
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html

